# Generated by Django 5.2.8 on 2025-12-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('is_deleted', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
